# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80 sudo lsof -i :80+sudo kill -9 PID
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
  error:
    path: /error
    include-message: always
    include-exception: true

#配置mybatisplus
mybatis-plus:
#  mapper-locations:
#    - classpath:mapper/*.xml
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration: #指定mybatis全局配置文件中的相关配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#数据源datasource配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #8.x版本驱动com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/warehouse?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: a87160265
    type: com.alibaba.druid.pool.DruidDataSource #使用druid
    druid:
      stat-view-servlet:  # 配置StatViewServlet
        enabled: true  #启用，默认是关闭的
        url-pattern: "/druid/*"
        allow: 127.0.0.1 #ip白名单
        #druid监控页登录账号
        login-username: admin
        login-password: 123456
        reset-enable: false #是否可以重置，页面充值按钮
        #deny: 192.168.1.102 #ip黑名单

      filters: stat,wall,slf4j # 配置监控统计拦截的filters和防火墙
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-log-enabled: false
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true
          result-set-log-enabled: false
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
          config:
            drop-table-allow: false #不允许出现删除表的操作

      web-stat-filter: # 配置StatFilter
        enabled: true #默认为false，设置为true启动
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      aop-patterns: com.example.warehouse.* # 配置spring容器组件的监控

  logging:
    level:
      druid:
        sql:
          Statement: debug

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 400MB

#  redis:
#    database: 0
#    host: 172.18.14.143        # Redis服务器地址 随着IP环境实时改变！！！！！！
#    port: 6379              # Redis服务器连接端口
#    password:               # Redis服务器连接密码（默认为空）
#    pool:
#      max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
#      max-idle: 10          # 连接池中的最大空闲连接
#      max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      min-idle: 0           # 连接池中的最小空闲连接
#    timeout: 1000           # 连接超时时间（毫秒）
#jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

